### ISSUE TITLE
install PyTorch version 2.3.1

### ISSUE THREAD

**Issue by HTsummer** [GrokCV/BAFE-Net#1]
conda install pytorch=2.3.1 torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia

**Comment by HTsummer** [comment]
我指定了11.8的cuda和2.3.1的pytorch，但是mmcv通过命令以及查阅英文文档，推荐安装的都是2.2.0，运行train的命令时始终会出错，可以参考一下作者的cuda，pytorch，mmcv的版本吗

**Comment by XMX969** [comment]
我的版本是：
mmcv==2.0.0
mmdet==3.0.0
mmengine==0.10.4
mmsegmentation==1.0.0
torch==2.0.1
torchaudio==2.0.2
torchvision==0.15.2
